<?php
    /** @var \Magento\Framework\Escaper $escaper */
    /** @var \Swissup\Testimonials\Block\TestimonialsList $block */
?>
<?php $testimonials = $block->getTestimonials(); ?>
<?php if (!$block->getIsAjax()): ?>
<div class="testimonials-list">
    <div class="testimonials" data-mage-init='{"Swissup_Testimonials/js/list":{"loadAction":"<?= $escaper->escapeUrl($block->getLoadAction()) ?>"}}'>
<?php endif; ?>
    <?php if($testimonials->getSize()): ?>
        <?php /** @var \Swissup\Testimonials\Model\Data $testimonial */ ?>
        <?php foreach ($testimonials as $testimonial): ?>
            <figure class="testimonial<?php if ($block->getIsAjax()): ?> loaded<?php endif;?>">
                <blockquote>
                    <?= $escaper->escapeHtml($testimonial->getMessage()); ?>
                    <div class="arrow"></div>
                    <div class="extra-info">
                        <small class="date nobr">
                            <?= $escaper->escapeHtml($block->formatDate($testimonial->getDate(), \IntlDateFormatter::LONG)) ?>
                        </small>
                        <?php if ($testimonial->getRating()): ?>
                        <?php $ratingPercent = $block->getRatingPercent($testimonial); ?>
                        <small class="rating nobr">
                            <div class="review-ratings">
                                <div class="rating-summary item">
                                    <span class="label rating-label">
                                        <span><?= $escaper->escapeHtml(__('Rating')) ?></span>
                                    </span>
                                    <div class="rating-result" title="<?= $escaper->escapeHtmlAttr($ratingPercent) ?>%">
                                        <span style="width:<?= $escaper->escapeHtmlAttr($ratingPercent) ?>%">
                                            <span><?= $escaper->escapeHtml($ratingPercent) ?>%</span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </small>
                    </div>
                    <?php endif; ?>
                </blockquote>
                <div class="info">
                    <img src="<?= $escaper->escapeUrl($block->getProfileImageUrl($testimonial)) ?>" alt="<?= $escaper->escapeHtmlAttr(__('Profile image')) ?>" />
                    <div class="author">
                        <div class="author-name"><?= $escaper->escapeHtml($testimonial->getName()) ?></div>
                        <?php
                        $company = $testimonial->getCompany();
                        $website = $testimonial->getWebsite();
                        if ($company && $website): ?>
                        <p class="author-company">
                            <a href="<?= $escaper->escapeUrl($website) ?>" target='_blank'>
                                <?= $escaper->escapeHtml($company) ?>
                            </a>
                        </p>
                        <?php endif; ?>
                        <?php
                        $email = $testimonial->getEmail();
                        $isShowUserEmail = !empty($email);
                        $facebook = $testimonial->getFacebook();
                        $isFacebookEnabled = !empty($facebook);
                        $twitter = $testimonial->getTwitter();
                        $isTwitterEnabled = !empty($twitter);
                        if ($isShowUserEmail || $isFacebookEnabled || $isTwitterEnabled): ?>
                        <p class="contacts-info">
                            <?php if ($isShowUserEmail): ?>
                            <a title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" href="mailto:<?= $escaper->escapeUrl($email) ?>" target="_blank">
                                <img src="<?= $escaper->escapeUrl($block->getEmailIconUrl()) ?>" />
                            </a>
                            <?php endif; ?>
                            <?php if ($isFacebookEnabled): ?>
                            <a title="<?= $escaper->escapeHtmlAttr(__('Facebook')) ?>" href="<?= $escaper->escapeUrl($facebook) ?>" target="_blank">
                                <img src="<?= $escaper->escapeUrl($block->getFacebookIconUrl()) ?>" />
                            </a>
                            <?php endif; ?>
                            <?php if ($isTwitterEnabled): ?>
                            <a title="<?= $escaper->escapeHtmlAttr(__('Twitter')) ?>" href="<?= $escaper->escapeUrl($twitter) ?>" target="_blank">
                                <img src="<?= $escaper->escapeUrl($block->getTwitterIconUrl()) ?>" />
                            </a>
                            <?php endif; ?>
                        </p>
                        <?php endif; ?>
                    </div>
                </div>
            </figure>
        <?php endforeach; ?>
    <?php else: ?>
        <p><?= $escaper->escapeHtml(__('No testimonials found.')); ?></p>
    <?php endif; ?>
<?php if (!$block->getIsAjax()): ?>
    </div>
    <?php if (!$block->isLastPage()): ?>
    <div class="more-button">
        <a id="viewMore" target="blank" href=""><?= $escaper->escapeHtml(__('Show more testimonials')) ?></a>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>
