<?php /** @var $block \Swissup\Testimonials\Block\TestimonialsList */ ?>
<h1><?php echo __('Testimonials') ?></h1>
<ul class="testimonials-list">
<?php /** @var $testimonial \Swissup\Testimonials\Model\Data */ ?>
<?php foreach ($block->getTestimonials() as $testimonial): ?>
    <li class="testimonial-list-item">
        <h3 class="testimonial-item-title">
            <?php echo $testimonial->getName() ?>
        </h3>

        <div class="testimonial-item-content">
            <?php echo $testimonial->getMessage(); ?>
        </div>

        <div class="testimonial-item-meta">
            <strong><?php echo __('Created at:') ?></strong> <?php echo $testimonial->getDate() ?>
        </div>
    </li>
<?php endforeach; ?>
</ul>