<?php /** @var $block \Swissup\Testimonials\Block\TestimonialsList */ ?>
<?php $testimonials = $block->getTestimonials(); ?>
<?php if (!$block->getIsAjax()): ?>
<div class="testimonials-list">
    <div class="testimonials" data-mage-init='{"Swissup_Testimonials/js/list":{"loadAction":"<?= $block->escapeUrl($block->getLoadAction()) ?>"}}'>
<?php endif; ?>
    <?php if($testimonials->getSize()): ?>
        <?php /** @var $testimonial \Swissup\Testimonials\Model\Data */ ?>
        <?php foreach ($testimonials as $testimonial): ?>
            <figure class="testimonial<?php if ($block->getIsAjax()): ?> loaded<?php endif;?>">
                <blockquote>
                    <?= $block->escapeHtml($testimonial->getMessage()); ?>
                    <div class="arrow"></div>
                    <div class="extra-info">
                        <small class="date nobr">
                            <?= $block->formatDate($testimonial->getDate(), \IntlDateFormatter::LONG) ?>
                        </small>
                        <?php if ($testimonial->getRating()): ?>
                        <?php $ratingPercent = $block->getRatingPercent($testimonial); ?>
                        <small class="rating nobr">
                            <div class="review-ratings">
                                <div class="rating-summary item">
                                    <span class="label rating-label">
                                        <span><?= __('Rating') ?></span>
                                    </span>
                                    <div class="rating-result" title="<?= $ratingPercent ?>%">
                                        <span style="width:<?= $ratingPercent ?>%">
                                            <span><?= $ratingPercent ?>%</span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </small>
                    </div>
                    <?php endif; ?>
                </blockquote>
                <div class="info">
                    <img src="<?= $block->getProfileImageUrl($testimonial) ?>" alt="Profile image" />
                    <div class="author">
                        <div class="author-name"><?= $block->escapeHtml($testimonial->getName()) ?></div>
                        <?php
                        $company = $testimonial->getCompany();
                        $website = $testimonial->getWebsite();
                        if ($company && $website): ?>
                        <p class="author-company">
                            <a href="<?= $block->escapeUrl($website) ?>" target='_blank'>
                                <?= $block->escapeHtml($company) ?>
                            </a>
                        </p>
                        <?php endif; ?>
                        <?php
                        $email = $testimonial->getEmail();
                        $isShowUserEmail = !empty($email);
                        $facebook = $testimonial->getFacebook();
                        $isFacebookEnabled = !empty($facebook);
                        $twitter = $testimonial->getTwitter();
                        $isTwitterEnabled = !empty($twitter);
                        if ($isShowUserEmail || $isFacebookEnabled || $isTwitterEnabled): ?>
                        <p class="contacts-info">
                            <?php if ($isShowUserEmail): ?>
                            <a title="<?= $block->escapeHtml(__('Email')) ?>" href="mailto:<?= $block->escapeHtml($email) ?>" target="_blank">
                                <img src="<?= $block->getEmailIconUrl() ?>" />
                            </a>
                            <?php endif; ?>
                            <?php if ($isFacebookEnabled): ?>
                            <a title="<?= $block->escapeHtml(__('Facebook')) ?>" href="<?= $block->escapeUrl($facebook) ?>" target="_blank">
                                <img src="<?= $block->getFacebookIconUrl() ?>" />
                            </a>
                            <?php endif; ?>
                            <?php if ($isTwitterEnabled): ?>
                            <a title="<?= $block->escapeHtml(__('Twitter')) ?>" href="<?= $block->escapeUrl($twitter) ?>" target="_blank">
                                <img src="<?= $block->getTwitterIconUrl() ?>" />
                            </a>
                            <?php endif; ?>
                        </p>
                        <?php endif; ?>
                    </div>
                </div>
            </figure>
        <?php endforeach; ?>
    <?php else: ?>
        <p><?= __('No testimonials found.'); ?></p>
    <?php endif; ?>
<?php if (!$block->getIsAjax()): ?>
    </div>
    <?php if (!$block->isLastPage()): ?>
    <div class="more-button">
        <a id="viewMore" target="blank" href=""><?= __('Show more testimonials') ?></a>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>
